apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app  : mysql
spec:
  type: ClusterIP
  ports:
  - name: port-mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app  : mysql
spec:
  replicas: 1
  selector:
    matchLabels:
       app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app  : mysql
    spec:
      containers:
      - name  : mysql
        image : mysql_image
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        volumeMounts:
        - name     : mysql-volume
          mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvclaim          
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 150Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql"
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvclaim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Mi

