apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app  : nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx_image
        imagePullPolicy: Never
        env:
        - name: PMA_ABSOLUTE_URI
          value: http://192.168.99.101:5000/
        ports:
        - containerPort: 80
        - containerPort: 443
