apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app : ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  ports:
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: pasv
      protocol: TCP
      port: 42000
      targetPort: 42000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 42000
          name: pasv

